language: go
install:
  - "go get -t -v ./..."
  - "go test -v ./..."
  - "go build -o bin/slex -v ."
deploy:
  provider: releases
  api_key:
    - secure: oEz2bY2j0AxQeG4/Kw3hKVwZOP+8OrUiRQ0SZhzX4ZH//9vOdzXIiNqFnk3NzdQeoMM9FiQ2ZxfxKFtMwmGTYc1+m6t90RjxWiLY6cdP4N4NhgLv9ynqWrxmSXacixrM7A5nkcnHsyAIPTEeehNihxpN9hyCDDMTu8nEE0z+5ULyVjysNKF+GM7FIJ3H+n43EX0DamGeRra1OBttm4khZFOMlikBzPNCvW4xtvDS2T+yBLLAqUJb0BKmNTGRg+8ghZ4SW86B8ELB26bEiBNpI2wD/HHZ36heJWkZGCd2u9O0iPHCBLPG4g/ut5QqUoNbgp4ducxbcfqXH161IAwI/+U9f1tTSBcP2Yx80tw6TfUq8gYgttFRtIGQ33CdiKCxlYyRakL/y9dtCEkODVHBpyteTA7IoEHuoDEO2z7UfvdOSc7uPxsJDl/btiCogk0ATvymK+GWiZl+nKmJO2urSWWqVNoMAqJjgBlxul5LZruN2aAzx/r5KIiROq88/eMDLsiAor4MFbMuSvsCcEiLDsBuV3z8U4Pg2XXzN7ooTMUIEfT2R1Cy9X2yq4HwruAJteDHzKRg7RE1ZySY2h5ISAOcQdQKVVCqhZQ6NRi71LjryrtS+VgCNXhI6fG08EoC+b261Xm/ARIyD9gCy/lq3qBJ4LstKISiSi0sDWYDmqw=
  file: bin/slex
  on:
    repo: christer79/slex
    all_branches: true
