language: go
install:
  - "go get -t -v ./..."
  - "go test -v ./..."
  - "go build -o bin/slex -v ."
deploy:
  provider: releases
  api_key:
    secure: TZytNqncfqB9Lv8Vh9FeygJywEmjAe1hF2pX0DCzW7JrRqBbiZqivZ/RC4SoqCe8Ym7yUEe4fUvqAZr5+xOHTPBoHL4sMBkNiXqnLezk7cQEmAa4BLIS57P7gGiR0pl0J/YA5482HXy3WiNa7/CtAw4uHCkyouJst5cAi9GzUteycDKtitW4WrufF7dk9LPSIFL4D8Hc5iTxJICcKqEbpB7aQ0c47uE2/oseMxDqmj0QwEds3N9D4P9O9ftX9USti4hSPWSOWslyWGWR+ZTRHFg7lh6YWaAU2hE81G260hUIzCaeOYItAZme1IldjMdMSm1dXLtG0k6tpvqiSU4Bp9B3U68mqRyqWPUdbOzkgtSxjw1Rz0hGPSuh58JnR8igxz68Y/NU/LJdCNcftA/kNQXO3DJKnDcSGxbqk1x+y37sfJnn2ywu8Try1XyGh5SurxQ9c4B8m+P9sh3ZhoZpYNNNjwrG9/0KAbvFtpgtV22HTc/FUwxKp4wLq754blp+/bfbl0aDP2S5N14pqkMNMp3BDmqtMbfuJVQ/298st+8eCMEwIToJ0e6kU1PAxgtvSS6jb3a2BZf9FklrIGgFtqtiPTVppI+dccVdMph91t8pvVD9jKbzRxhyHovVbwTvXgeMrGQqXPozm6Yj+WuPpgLXSiU3aO0W2xmVSL3KNrQ=
  file: bin/slex
  on:
    repo: christer79/slex
    all_branches: true
